
package rsoi.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWebService", targetNamespace = "http://WebService.rsoi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDoc", targetNamespace = "http://WebService.rsoi/", className = "rsoi.webservice.UpdateDoc")
    @ResponseWrapper(localName = "updateDocResponse", targetNamespace = "http://WebService.rsoi/", className = "rsoi.webservice.UpdateDocResponse")
    @Action(input = "http://WebService.rsoi/IWebService/updateDocRequest", output = "http://WebService.rsoi/IWebService/updateDocResponse")
    public String updateDoc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns rsoi.webservice.StateProgDoc
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDoc", targetNamespace = "http://WebService.rsoi/", className = "rsoi.webservice.CreateDoc")
    @ResponseWrapper(localName = "createDocResponse", targetNamespace = "http://WebService.rsoi/", className = "rsoi.webservice.CreateDocResponse")
    @Action(input = "http://WebService.rsoi/IWebService/createDocRequest", output = "http://WebService.rsoi/IWebService/createDocResponse")
    public StateProgDoc createDoc(
        @WebParam(name = "arg0", targetNamespace = "")
        StateProgDoc arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        DocumentClass arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scaleDateEnd", targetNamespace = "http://WebService.rsoi/", className = "rsoi.webservice.ScaleDateEnd")
    @ResponseWrapper(localName = "scaleDateEndResponse", targetNamespace = "http://WebService.rsoi/", className = "rsoi.webservice.ScaleDateEndResponse")
    @Action(input = "http://WebService.rsoi/IWebService/scaleDateEndRequest", output = "http://WebService.rsoi/IWebService/scaleDateEndResponse")
    public String scaleDateEnd(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

}
