
package rsoi.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceImpService", targetNamespace = "http://WebService.rsoi/", wsdlLocation = "http://localhost:8081/ts?WSDL")
public class WebServiceImpService
    extends Service
{

    private final static URL WEBSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEIMPSERVICE_EXCEPTION;
    private final static QName WEBSERVICEIMPSERVICE_QNAME = new QName("http://WebService.rsoi/", "WebServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ts?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEIMPSERVICE_WSDL_LOCATION = url;
        WEBSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public WebServiceImpService() {
        super(__getWsdlLocation(), WEBSERVICEIMPSERVICE_QNAME);
    }

    public WebServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEIMPSERVICE_QNAME, features);
    }

    public WebServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEIMPSERVICE_QNAME);
    }

    public WebServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEIMPSERVICE_QNAME, features);
    }

    public WebServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWebService
     */
    @WebEndpoint(name = "WebServiceImpPort")
    public IWebService getWebServiceImpPort() {
        return super.getPort(new QName("http://WebService.rsoi/", "WebServiceImpPort"), IWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebService
     */
    @WebEndpoint(name = "WebServiceImpPort")
    public IWebService getWebServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebService.rsoi/", "WebServiceImpPort"), IWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEIMPSERVICE_EXCEPTION;
        }
        return WEBSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
