
package rsoi.model;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IModel", targetNamespace = "http://model.rsoi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IModel {


    /**
     * 
     * @param arg0
     * @return
     *     returns rsoi.model.StateProgDoc
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getParent", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetParentResponse")
    @Action(input = "http://model.rsoi/IModel/getParentRequest", output = "http://model.rsoi/IModel/getParentResponse")
    public StateProgDoc getParent(
        @WebParam(name = "arg0", targetNamespace = "")
        StateProgDoc arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns rsoi.model.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorizeUser", targetNamespace = "http://model.rsoi/", className = "rsoi.model.AuthorizeUser")
    @ResponseWrapper(localName = "authorizeUserResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.AuthorizeUserResponse")
    @Action(input = "http://model.rsoi/IModel/authorizeUserRequest", output = "http://model.rsoi/IModel/authorizeUserResponse")
    public User authorizeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerNewUser", targetNamespace = "http://model.rsoi/", className = "rsoi.model.RegisterNewUser")
    @ResponseWrapper(localName = "registerNewUserResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.RegisterNewUserResponse")
    @Action(input = "http://model.rsoi/IModel/registerNewUserRequest", output = "http://model.rsoi/IModel/registerNewUserResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://model.rsoi/IModel/registerNewUser/Fault/Exception")
    })
    public boolean registerNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<rsoi.model.StateProgDoc>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStateProgDoc", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetAllStateProgDoc")
    @ResponseWrapper(localName = "getAllStateProgDocResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetAllStateProgDocResponse")
    @Action(input = "http://model.rsoi/IModel/getAllStateProgDocRequest", output = "http://model.rsoi/IModel/getAllStateProgDocResponse")
    public List<StateProgDoc> getAllStateProgDoc();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<rsoi.model.StateProgDoc>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubProgram", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetSubProgram")
    @ResponseWrapper(localName = "getSubProgramResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetSubProgramResponse")
    @Action(input = "http://model.rsoi/IModel/getSubProgramRequest", output = "http://model.rsoi/IModel/getSubProgramResponse")
    public List<StateProgDoc> getSubProgram(
        @WebParam(name = "arg0", targetNamespace = "")
        StateProgDoc arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<rsoi.model.StateProgDoc>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChildren", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetChildrenResponse")
    @Action(input = "http://model.rsoi/IModel/getChildrenRequest", output = "http://model.rsoi/IModel/getChildrenResponse")
    public List<StateProgDoc> getChildren(
        @WebParam(name = "arg0", targetNamespace = "")
        StateProgDoc arg0);

    /**
     * 
     * @return
     *     returns java.util.List<rsoi.model.Org>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllOrg", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetAllOrg")
    @ResponseWrapper(localName = "getAllOrgResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetAllOrgResponse")
    @Action(input = "http://model.rsoi/IModel/getAllOrgRequest", output = "http://model.rsoi/IModel/getAllOrgResponse")
    public List<Org> getAllOrg();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProgramm", targetNamespace = "http://model.rsoi/", className = "rsoi.model.CreateProgramm")
    @ResponseWrapper(localName = "createProgrammResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.CreateProgrammResponse")
    @Action(input = "http://model.rsoi/IModel/createProgrammRequest", output = "http://model.rsoi/IModel/createProgrammResponse")
    public boolean createProgramm(
        @WebParam(name = "arg0", targetNamespace = "")
        StateProgDoc arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createOrg", targetNamespace = "http://model.rsoi/", className = "rsoi.model.CreateOrg")
    @ResponseWrapper(localName = "createOrgResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.CreateOrgResponse")
    @Action(input = "http://model.rsoi/IModel/createOrgRequest", output = "http://model.rsoi/IModel/createOrgResponse")
    public boolean createOrg(
        @WebParam(name = "arg0", targetNamespace = "")
        Org arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteOrg", targetNamespace = "http://model.rsoi/", className = "rsoi.model.DeleteOrg")
    @ResponseWrapper(localName = "deleteOrgResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.DeleteOrgResponse")
    @Action(input = "http://model.rsoi/IModel/deleteOrgRequest", output = "http://model.rsoi/IModel/deleteOrgResponse")
    public boolean deleteOrg(
        @WebParam(name = "arg0", targetNamespace = "")
        Org arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSubProgramm", targetNamespace = "http://model.rsoi/", className = "rsoi.model.CreateSubProgramm")
    @ResponseWrapper(localName = "createSubProgrammResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.CreateSubProgrammResponse")
    @Action(input = "http://model.rsoi/IModel/createSubProgrammRequest", output = "http://model.rsoi/IModel/createSubProgrammResponse")
    public boolean createSubProgramm(
        @WebParam(name = "arg0", targetNamespace = "")
        StateProgDoc arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        StateProgDoc arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns rsoi.model.Org
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrg", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetOrg")
    @ResponseWrapper(localName = "getOrgResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.GetOrgResponse")
    @Action(input = "http://model.rsoi/IModel/getOrgRequest", output = "http://model.rsoi/IModel/getOrgResponse")
    public Org getOrg(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns rsoi.model.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testServise", targetNamespace = "http://model.rsoi/", className = "rsoi.model.TestServise")
    @ResponseWrapper(localName = "testServiseResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.TestServiseResponse")
    @Action(input = "http://model.rsoi/IModel/testServiseRequest", output = "http://model.rsoi/IModel/testServiseResponse")
    public User testServise(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns rsoi.model.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testDao", targetNamespace = "http://model.rsoi/", className = "rsoi.model.TestDao")
    @ResponseWrapper(localName = "testDaoResponse", targetNamespace = "http://model.rsoi/", className = "rsoi.model.TestDaoResponse")
    @Action(input = "http://model.rsoi/IModel/testDaoRequest", output = "http://model.rsoi/IModel/testDaoResponse")
    public User testDao(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
